name: Python package

on: 
  push: 
    branches: [ "main" ]
  
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: if [ -d ~/.cache ]; then ls -l ~/.cache; else echo "Cache dir does not exist"; fi
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
